name: Enhanced PR Quality Check

# è§¸ç™¼æ¢ä»¶
on:
  pull_request:

    branches: [main, develop]

  push:

    branches: [main, develop]

  workflow_dispatch:  # å…è¨±æ‰‹å‹•è§¸ç™¼


# ç’°å¢ƒè®Šé‡
env:
  PYTHON_VERSION: '3.11'

  NODE_VERSION: '18'


jobs:
  # ä¸¦è¡ŒåŸ·è¡Œçš„æª¢æŸ¥å·¥ä½œ

  parallel-quality-checks:

    name: ${{ matrix.check-name }}

    runs-on: ubuntu-latest

    
    strategy:

      fail-fast: false  # ä¸€å€‹æª¢æŸ¥å¤±æ•—ä¸å½±éŸ¿å…¶ä»–æª¢æŸ¥

      matrix:

        check-name: [security, formatting, linting, typing, documentation]

        include:

          - check-name: security

            continue-on-error: true  # å®‰å…¨æª¢æŸ¥éžé˜»å¡ž

            critical: false

          - check-name: formatting

            continue-on-error: false

            critical: true

          - check-name: linting

            continue-on-error: false

            critical: true

          - check-name: typing

            continue-on-error: true  # é¡žåž‹æª¢æŸ¥éžé˜»å¡ž

            critical: false

          - check-name: documentation

            continue-on-error: true

            critical: false

    
    steps:

      - name: Checkout code

        uses: actions/checkout@v3

        with:

          fetch-depth: 0  # ç²å–å®Œæ•´æ­·å²ç”¨æ–¼æ›´å¥½çš„åˆ†æž

      
      # è¨­ç½® Python ç’°å¢ƒ

      - name: Set up Python

        uses: actions/setup-python@v4

        with:

          python-version: ${{ env.PYTHON_VERSION }}

          cache: 'pip'

      
      # å®‰è£ä¾è³´

      - name: Install dependencies

        run: |

          python -m pip install --upgrade pip

          pip install black ruff mypy bandit detect-secrets interrogate pylint

          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      
      # å®‰è£ Node.jsï¼ˆå¦‚æžœéœ€è¦ï¼‰

      - name: Set up Node.js

        if: matrix.check-name == 'documentation'

        uses: actions/setup-node@v3

        with:

          node-version: ${{ env.NODE_VERSION }}

          cache: 'npm'

      
      # åŸ·è¡Œå…·é«”æª¢æŸ¥

      - name: Run ${{ matrix.check-name }} check

        continue-on-error: ${{ matrix.continue-on-error }}

        run: |

          echo "Running ${{ matrix.check-name }} check..."

          case "${{ matrix.check-name }}" in

            security)

              echo "Running Bandit security scan..."

              bandit -r workspace/src/ 00-namespaces/ -f json -o bandit-report.json || true

              echo "::notice::Security scan completed. Review bandit-report.json for details."

              
              if [ -f bandit-report.json ] && [ -s bandit-report.json ]; then

                ISSUES_COUNT=$(cat bandit-report.json | jq '.results | length' 2>/dev/null || echo "0")

                echo "::notice::Found $ISSUES_COUNT security issues (informational only)"

              fi

              ;;

            
            formatting)

              echo "Checking code formatting with Black..."

              black --check workspace/src/ 00-namespaces/

              echo "::notice::Code formatting check passed"

              ;;

            
            linting)

              echo "Linting code with Ruff..."

              ruff check workspace/src/ 00-namespaces/

              echo "::notice::Code linting check passed"

              ;;

            
            typing)

              echo "Type checking with MyPy..."

              mypy workspace/src/ 00-namespaces/ --no-error-summary || echo "::warning::Type checking issues found"

              echo "::notice::Type checking completed"

              ;;

            
            documentation)

              echo "Checking documentation coverage..."

              interrogate -vv workspace/src/ 00-namespaces/ --fail-under 85 || echo "::warning::Documentation coverage below 85%"

              echo "::notice::Documentation check completed"

              ;;

          esac

      
      # ä¸Šå‚³æª¢æŸ¥çµæžœ

      - name: Upload ${{ matrix.check-name }} results

        if: always()

        uses: actions/upload-artifact@v3

        with:

          name: ${{ matrix.check-name }}-results

          path: |

            bandit-report.json

            *.log

          retention-days: 30

          if-no-files-found: warn


  # ç¶œåˆè³ªé‡å ±å‘Š

  generate-quality-report:

    name: Generate Quality Report

    runs-on: ubuntu-latest

    needs: [parallel-quality-checks]

    if: always()  # å³ä½¿æŸäº›æª¢æŸ¥å¤±æ•—ä¹Ÿç”Ÿæˆå ±å‘Š

    
    steps:

      - name: Checkout code

        uses: actions/checkout@v3

      
      - name: Download all artifacts

        uses: actions/download-artifact@v3

        with:

          path: ./artifacts

      
      - name: Set up Python

        uses: actions/setup-python@v4

        with:

          python-version: ${{ env.PYTHON_VERSION }}

      
      - name: Generate comprehensive report

        run: |

          cat > quality-report.md << 'EOF'

          # PR Quality Check Report

          
          ## ðŸ“Š Summary

          
          - **Repository**: ${{ github.repository }}

          - **PR Number**: ${{ github.event.pull_request.number }}

          - **Branch**: ${{ github.head_ref }}

          - **Commit**: ${{ github.sha }}

          - **Triggered by**: ${{ github.actor }}

          - **Timestamp**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

          
          ## ðŸ” Check Results

          
          EOF

          
          # åˆ†æžå„å€‹æª¢æŸ¥çš„çµæžœ

          for dir in ./artifacts/*-results; do

            if [ -d "$dir" ]; then

              check_name=$(basename "$dir" | sed 's/-results//')

              echo "### $check_name" >> quality-report.md

              
              if [ -f "$dir/bandit-report.json" ]; then

                echo "Security scan completed successfully." >> quality-report.md

              else

                echo "Check completed." >> quality-report.md

              fi

              
              echo "" >> quality-report.md

            fi

          done

          
          cat >> quality-report.md << 'EOF'

          
          ## ðŸ“ Notes

          
          - Security checks are informational and won't block PRs

          - Formatting and linting checks are critical and must pass

          - Type checking and documentation are warnings

          
          ## ðŸ”— Resources

          
          - [View Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          - [View PR](${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }})

          
          EOF

          
          cat quality-report.md

      
      - name: Upload quality report

        uses: actions/upload-artifact@v3

        with:

          name: quality-report

          path: quality-report.md

      
      - name: Comment on PR

        if: github.event_name == 'pull_request'

        uses: actions/github-script@v6

        with:

          script: |

            const fs = require('fs');

            const report = fs.readFileSync('quality-report.md', 'utf8');

            
            // å°‹æ‰¾ç¾æœ‰çš„è©•è«–

            const comments = await github.rest.issues.listComments({

              owner: context.repo.owner,

              repo: context.repo.repo,

              issue_number: context.issue.number,

            });

            
            // åˆªé™¤èˆŠçš„è©•è«–

            for (const comment of comments.data) {

              if (comment.user.type === 'Bot' && comment.body.includes('PR Quality Check Report')) {

                await github.rest.issues.deleteComment({

                  owner: context.repo.owner,

                  repo: context.repo.repo,

                  comment_id: comment.id

                });

              }

            }

            
            // æ·»åŠ æ–°è©•è«–

            await github.rest.issues.createComment({

              owner: context.repo.owner,

              repo: context.repo.repo,

              issue_number: context.issue.number,

              body: report

            });


  # é€šçŸ¥å·¥ä½œæµ

  notify-team:

    name: Notify Team

    runs-on: ubuntu-latest

    needs: [parallel-quality-checks]

    if: failure()  # åªåœ¨å¤±æ•—æ™‚é€šçŸ¥

    
    steps:

      - name: Send failure notification

        run: |

          echo "Critical checks failed. Team should be notified."

          # é€™è£¡å¯ä»¥é›†æˆ Slackã€Email æˆ–å…¶ä»–é€šçŸ¥ç³»çµ±

          echo "::error::Critical quality checks failed. Please review the workflow run."


  # ä¾è³´é …æ¼æ´žæŽƒæï¼ˆå¯é¸ï¼‰

  dependency-vulnerability-scan:

    name: Dependency Vulnerability Scan

    runs-on: ubuntu-latest

    
    steps:

      - name: Checkout code

        uses: actions/checkout@v3

      
      - name: Run Trivy vulnerability scanner

        uses: aquasecurity/trivy-action@master

        with:

          scan-type: 'fs'

          scan-ref: '.'

          format: 'sarif'

          output: 'trivy-results.sarif'

      
      - name: Upload Trivy results to GitHub Security tab

        uses: github/codeql-action/upload-sarif@v2

        with:

          sarif_file: 'trivy-results.sarif'
