#!/bin/bash
# Auto-generated script to fix hardcoded URLs
# Run this to backup files before making changes

echo 'Creating backups...'
mkdir -p backup_phase4b

cp machine-native-ops/00-namespaces/namespaces-mcp/level1/verification/github-oauth-verifier.py backup_phase4b/
cp workspace/src/services/agents/dependency-manager/src/analyzers/go_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/tools/docs/project_to_superroot.py backup_phase4b/
cp workspace/mcp/validation-mcp/tools/github_project_analyzer_v2.py backup_phase4b/
cp workspace/src/services/agents/dependency-manager/src/analyzers/npm_analyzer.py backup_phase4b/
cp workspace/teams/holy-grail/dissolved-assets/tools/github_project_analyzer_v2.py backup_phase4b/
cp workspace/tools/docs/scan_repo_generate_index.py backup_phase4b/
cp machine-native-ops/workspace/tools/docs/provenance_injector.py backup_phase4b/
cp workspace/tools/docs/generate_mndoc_from_readme.py backup_phase4b/
cp machine-native-ops/controlplane/validation/supply-chain-complete-verifier.py backup_phase4b/
cp workspace/src/apps/web-backend/services/api.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/agents/ai-experts/dependency-manager/src/analyzers/pip_analyzer.py backup_phase4b/
cp workspace/src/ai/agents/dependency-manager/src/scanners/vulnerability_scanner.py backup_phase4b/
cp 00-namespaces/namespaces-mcp/level1/validation/extended-validator.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/agents/ai-experts/dependency-manager/src/analyzers/npm_analyzer.py backup_phase4b/
cp workspace/src/core/engine/function_calling.py backup_phase4b/
cp workspace/src/core/plugins/yaml_module_system/slsa_compliance.py backup_phase4b/
cp machine-native-ops/workspace/src/enterprise/iam/sso.py backup_phase4b/
cp workspace/root/teams/default-team/orchestrator/services/github_integration.py backup_phase4b/
cp machine-native-ops/workspace/src/developer-tools/team-collaboration-platform/collaboration_hub.py backup_phase4b/
cp workspace/src/core/plugins/tech_stack/architecture_config.py backup_phase4b/
cp machine-native-ops/00-namespaces/namespaces-mcp/level1/instant-system/deployer.py backup_phase4b/
cp machine-native-ops/workspace/src/enterprise/integrations/providers.py backup_phase4b/
cp workspace/src/developer-tools/code-complexity-analyzer/complexity_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/engine/machinenativenops-auto-monitor/setup.py backup_phase4b/
cp workspace/src/enterprise/integrations/providers.py backup_phase4b/
cp machine-native-ops/workspace/src/core/yaml_module_system/slsa_compliance.py backup_phase4b/
cp workspace/teams/holy-grail/agents/ai-experts/dependency-manager/src/analyzers/pip_analyzer.py backup_phase4b/
cp workspace/tools/evidence_generator.py backup_phase4b/
cp workspace/src/enterprise/iam/sso.py backup_phase4b/
cp machine-native-ops/00-namespaces/namespaces-mcp/level1/validation/extended-validator.py backup_phase4b/
cp workspace/tools/scripts/vulnerability-alert-handler.py backup_phase4b/
cp workspace/tools/docs/project_to_superroot.py backup_phase4b/
cp machine-native-ops/workspace/src/ci-tools/monitoring-alerting/monitoring_system.py backup_phase4b/
cp workspace/tools/scripts/manage-secret-patterns.py backup_phase4b/
cp workspace/src/governance/scripts/generate_dimensions.py backup_phase4b/
cp machine-native-ops/workspace/setup.py backup_phase4b/
cp workspace/src/frontend/ui/services/api.py backup_phase4b/
cp machine-native-ops/workspace/src/frontend/ui/services/api.py backup_phase4b/
cp machine-native-ops/workspace/src/services/agents/dependency-manager/src/scanners/vulnerability_scanner.py backup_phase4b/
cp machine-native-ops/workspace/src/services/agents/dependency-manager/src/analyzers/pip_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/src/core/slsa_provenance/provenance_generator.py backup_phase4b/
cp machine-native-ops/workspace/src/developer-tools/code-complexity-analyzer/complexity_analyzer.py backup_phase4b/
cp workspace/tools/docs/pr_comment_summary.py backup_phase4b/
cp workspace/src/enterprise/execution/supply_chain.py backup_phase4b/
cp machine-native-ops/workspace/tools/docs/generate_mndoc_from_readme.py backup_phase4b/
cp controlplane/validation/supply-chain-complete-verifier.py backup_phase4b/
cp workspace/src/services/agents/dependency-manager/src/scanners/vulnerability_scanner.py backup_phase4b/
cp workspace/config/integrations/jira-integration.py backup_phase4b/
cp machine-native-ops/workspace/src/core/tech_stack/architecture_config.py backup_phase4b/
cp workspace/src/core/plugins/tech_stack/python_bridge.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/dissolved-assets/tools/github_project_analyzer_v2.py backup_phase4b/
cp machine-native-ops/workspace/tools/docs/pr_comment_summary.py backup_phase4b/
cp machine-native-ops/workspace/src/core/slsa_provenance/signature_verifier.py backup_phase4b/
cp machine-native-ops/workspace/tools/scripts/manage-secret-patterns.py backup_phase4b/
cp workspace/src/autonomous/infrastructure/config/integrations/jira-integration.py backup_phase4b/
cp machine-native-ops/workspace/src/core/engine/function_calling.py backup_phase4b/
cp workspace/tools/sync_external_repos.py backup_phase4b/
cp workspace/src/core/yaml_module_system/slsa_compliance.py backup_phase4b/
cp workspace/teams/holy-grail/dissolved-assets/tools/github_project_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/tools/scripts/vulnerability-alert-handler.py backup_phase4b/
cp workspace/tools/automation/engines/baseline_validation_engine.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/agents/ai-experts/dependency-manager/src/analyzers/go_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/src/core/plugins/yaml_module_system/slsa_compliance.py backup_phase4b/
cp machine-native-ops/workspace/src/governance/scripts/generate_dimensions.py backup_phase4b/
cp workspace/teams/holy-grail/dissolved-assets/tools/github_project_analyzer_quantum.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/agents/services/dependency-manager/src/analyzers/npm_analyzer.py backup_phase4b/
cp workspace/teams/holy-grail/agents/services/dependency-manager/src/analyzers/go_analyzer.py backup_phase4b/
cp workspace/src/enterprise/integrations/writeback.py backup_phase4b/
cp workspace/src/developer-tools/team-collaboration-platform/collaboration_hub.py backup_phase4b/
cp workspace/teams/holy-grail/agents/ai-experts/dependency-manager/src/analyzers/go_analyzer.py backup_phase4b/
cp workspace/teams/holy-grail/agents/services/dependency-manager/src/scanners/vulnerability_scanner.py backup_phase4b/
cp workspace/tools/docs/generate_knowledge_graph.py backup_phase4b/
cp machine-native-ops/workspace/tools/docs/generate_knowledge_graph.py backup_phase4b/
cp machine-native-ops/workspace/src/core/plugins/tech_stack/python_bridge.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/dissolved-assets/tools/github_project_analyzer.py backup_phase4b/
cp workspace/scripts/github/fix-actions-sha.py backup_phase4b/
cp workspace/src/services/agents/dependency-manager/src/analyzers/pip_analyzer.py backup_phase4b/
cp workspace/tools/docs/provenance_injector.py backup_phase4b/
cp machine-native-ops/workspace/tools/automation/engines/baseline_validation_engine.py backup_phase4b/
cp machine-native-ops/workspace/src/ai/agents/dependency-manager/src/scanners/vulnerability_scanner.py backup_phase4b/
cp workspace/mcp/validation-mcp/tools/github_project_analyzer_quantum.py backup_phase4b/
cp workspace/mcp/validation-mcp/tools/github_project_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/agents/services/dependency-manager/src/analyzers/go_analyzer.py backup_phase4b/
cp workspace/teams/holy-grail/agents/services/dependency-manager/src/analyzers/npm_analyzer.py backup_phase4b/
cp workspace/teams/default-team/orchestrator/services/github_integration.py backup_phase4b/
cp machine-native-ops/workspace/src/autonomous/infrastructure/config/integrations/jira-integration.py backup_phase4b/
cp workspace/teams/holy-grail/agents/ai-experts/dependency-manager/src/analyzers/npm_analyzer.py backup_phase4b/
cp workspace/src/core/tech_stack/python_bridge.py backup_phase4b/
cp machine-native-ops/workspace/src/services/agents/dependency-manager/src/analyzers/npm_analyzer.py backup_phase4b/
cp 00-namespaces/namespaces-mcp/level1/verification/github-oauth-verifier.py backup_phase4b/
cp workspace/src/ai/agents/dependency-manager/src/analyzers/pip_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/src/ai/agents/dependency-manager/src/analyzers/pip_analyzer.py backup_phase4b/
cp workspace/teams/holy-grail/agents/services/dependency-manager/src/analyzers/pip_analyzer.py backup_phase4b/
cp workspace/src/ai/agents/dependency-manager/src/analyzers/npm_analyzer.py backup_phase4b/
cp workspace/teams/holy-grail/agents/ai-experts/dependency-manager/src/scanners/vulnerability_scanner.py backup_phase4b/
cp machine-native-ops/workspace/tools/docs/scan_repo_generate_index.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/dissolved-assets/tools/github_project_analyzer_quantum.py backup_phase4b/
cp workspace/src/ci-tools/monitoring-alerting/monitoring_system.py backup_phase4b/
cp machine-native-ops/workspace/src/ai/agents/dependency-manager/src/analyzers/go_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/mcp/validation-mcp/tools/github_project_analyzer_v2.py backup_phase4b/
cp machine-native-ops/workspace/tools/evidence_generator.py backup_phase4b/
cp machine-native-ops/workspace/root/teams/default-team/orchestrator/services/github_integration.py backup_phase4b/
cp workspace/engine/machinenativenops-auto-monitor/setup.py backup_phase4b/
cp machine-native-ops/workspace/tools/ci-cost-dashboard.py backup_phase4b/
cp machine-native-ops/workspace/src/services/agents/dependency-manager/src/analyzers/go_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/scripts/github/fix-actions-sha.py backup_phase4b/
cp machine-native-ops/workspace/teams/default-team/orchestrator/services/github_integration.py backup_phase4b/
cp machine-native-ops/workspace/config/integrations/jira-integration.py backup_phase4b/
cp machine-native-ops/workspace/src/enterprise/execution/supply_chain.py backup_phase4b/
cp machine-native-ops/workspace/src/ai/agents/dependency-manager/src/analyzers/npm_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/mcp/validation-mcp/tools/github_project_analyzer_quantum.py backup_phase4b/
cp machine-native-ops/workspace/tools/sync_external_repos.py backup_phase4b/
cp machine-native-ops/workspace/src/enterprise/integrations/writeback.py backup_phase4b/
cp machine-native-ops/workspace/mcp/validation-mcp/tools/github_project_analyzer.py backup_phase4b/
cp workspace/src/ai/agents/dependency-manager/src/analyzers/go_analyzer.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/agents/services/dependency-manager/src/scanners/vulnerability_scanner.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/agents/services/dependency-manager/src/analyzers/pip_analyzer.py backup_phase4b/
cp workspace/setup.py backup_phase4b/
cp workspace/src/core/slsa_provenance/signature_verifier.py backup_phase4b/
cp machine-native-ops/workspace/src/core/plugins/tech_stack/architecture_config.py backup_phase4b/
cp workspace/src/core/slsa_provenance/provenance_generator.py backup_phase4b/
cp machine-native-ops/workspace/src/core/tech_stack/python_bridge.py backup_phase4b/
cp 00-namespaces/namespaces-mcp/level1/instant-system/deployer.py backup_phase4b/
cp workspace/tools/ci-cost-dashboard.py backup_phase4b/
cp machine-native-ops/workspace/teams/holy-grail/agents/ai-experts/dependency-manager/src/scanners/vulnerability_scanner.py backup_phase4b/
cp workspace/src/core/tech_stack/architecture_config.py backup_phase4b/
cp machine-native-ops/workspace/src/apps/web-backend/services/api.py backup_phase4b/

echo 'Backups created in backup_phase4b/'
echo 'Please review the changes manually before committing'
