# Root Semantic Root Configuration
# Machine Native Ops - Semantic Root Version Management
# Version: 1.0.0
# Purpose: Central semantic root for all artifacts in the system

apiVersion: machinenativeops.io/v1
kind: SemanticRoot
metadata:
  name: machinenativeops-semantic-root
  version: 1.0.0
  namespace: machinenativeops-root
  labels:
    machinenativeops.io/tier: "semantic-root"
    machinenativeops.io/version: "1.0.0"
    machinenativeops.io/component: "semantic-root"
  annotations:
    machinenativeops.io/description: "Central semantic root for Machine Native Ops taxonomy and governance"
    machinenativeops.io/created: "2025-01-10T10:00:00Z"
    machinenativeops.io/author: "System Architecture Team"

spec:
  # === SEMANTIC ROOT METADATA ===
  semantic_root:
    name: "MachineNativeOps Semantic Root"
    version: "1.0.0"
    namespace: "machinenativeops-root"
    description: "Central semantic root for all artifacts, concepts, and governance policies"
    
    # Semantic root evolution
    evolution:
      current_version: "1.0.0"
      min_compatible_version: "1.0.0"
      next_version_candidate: "1.1.0"
      
      # Version history
      history:
        - version: "1.0.0"
          release_date: "2025-01-10T10:00:00Z"
          changes:
            - "Initial semantic root establishment"
            - "Define core concepts and structures"
            - "Establish governance framework"
          artifacts_count: 0
    
    # Semantic root consistency
    consistency:
      validation_enabled: true
      validation_interval: 60  # seconds
      auto_repair_enabled: false
      drift_detection_enabled: true
      drift_threshold: 0.01  # 1% drift tolerance

  # === CORE CONCEPTS ===
  concepts:
    # Base concepts (level 0)
    base_concepts:
      - name: "Artifact"
        definition: "Any entity in the system that can be versioned, governed, and traced"
        category: "structural"
        stability: "stable"
        fields:
          - name: "metadata"
            type: "object"
            required: true
            description: "Artifact identification and metadata"
          - name: "spec"
            type: "object"
            required: true
            description: "Artifact specification"
          - name: "status"
            type: "object"
            required: true
            description: "Artifact runtime status"
        examples:
          - "Configuration file"
          - "Service definition"
          - "Policy document"
      
      - name: "Governance"
        definition: "System of policies, procedures, and mechanisms that regulate behavior"
        category: "governance"
        stability: "stable"
        fields:
          - name: "policies"
            type: "array"
            required: true
            description: "Governance policies"
          - name: "roles"
            type: "array"
            required: true
            description: "RBAC roles and permissions"
          - name: "audit"
            type: "object"
            required: false
            description: "Audit trail configuration"
        examples:
          - "Access control policy"
          - "Compliance requirements"
          - "Audit logging"
      
      - name: "Module"
        definition: "Self-contained unit of functionality with defined interfaces and dependencies"
        category: "structural"
        stability: "stable"
        fields:
          - name: "entrypoint"
            type: "string"
            required: true
            description: "Module execution entry point"
          - name: "dependencies"
            type: "array"
            required: true
            description: "Module dependencies"
          - name: "health_check"
            type: "object"
            required: true
            description: "Health check configuration"
        examples:
          - "Governance engine module"
          - "Trust manager module"
          - "Provenance service module"
      
      - name: "Trust"
        definition: "System of establishing and maintaining trust relationships between entities"
        category: "security"
        stability: "stable"
        fields:
          - name: "certificate_chain"
            type: "array"
            required: true
            description: "Trust certificate chain"
          - name: "signature"
            type: "string"
            required: true
            description: "Cryptographic signature"
          - name: "verification"
            type: "object"
            required: true
            description: "Verification configuration"
        examples:
          - "Certificate-based trust"
          - "Signature verification"
          - "Key rotation"
      
      - name: "Provenance"
        definition: "Complete record of the origin, history, and lifecycle of an artifact"
        category: "traceability"
        stability: "stable"
        fields:
          - name: "origin"
            type: "object"
            required: true
            description: "Artifact origin information"
          - name: "modifications"
            type: "array"
            required: true
            description: "Modification history"
          - name: "signatures"
            type: "array"
            required: true
            description: "Provenance signatures"
        examples:
          - "Source code origin"
          - "Build provenance"
          - "Deployment history"
      
      - name: "Integrity"
        definition: "System for ensuring and verifying the consistency and authenticity of artifacts"
        category: "security"
        stability: "stable"
        fields:
          - name: "hash"
            type: "string"
            required: true
            description: "Cryptographic hash"
          - name: "hash_algorithm"
            type: "string"
            required: true
            description: "Hash algorithm used"
          - name: "signature"
            type: "string"
            required: true
            description: "Integrity signature"
        examples:
          - "Hash lock"
          - "Drift detection"
          - "Signature verification"
      
      - name: "Execution"
        definition: "Flow and orchestration of system operations and workflows"
        category: "operational"
        stability: "stable"
        fields:
          - name: "workflows"
            type: "array"
            required: true
            description: "Execution workflows"
          - name: "triggers"
            type: "array"
            required: true
            description: "Execution triggers"
          - name: "state_management"
            type: "object"
            required: true
            description: "Execution state management"
        examples:
          - "Deployment workflow"
          - "Validation pipeline"
          - "Rollback procedure"

    # Derived concepts (level 1+)
    derived_concepts:
      - name: "FileXArtifact"
        extends: "Artifact"
        definition: "Artifact following FileX Standard Template v1 with bi-directional governance"
        category: "structural"
        stability: "experimental"
        features:
          - "Forward expansion"
          - "Backward reconciliation"
          - "Semantic closure validation"
          - "Attestation bundle generation"
      
      - name: "BiDirectionalGovernance"
        extends: "Governance"
        definition: "Governance system with both forward and backward reconciliation mechanisms"
        category: "governance"
        stability: "experimental"
        features:
          - "Semantic root consistency"
          - "Dependency closure validation"
          - "Automatic patch generation"
          - "Governance closure enforcement"

  # === NAMING CONVENTIONS ===
  naming_conventions:
    # Artifact naming
    artifact_naming:
      pattern: "^[a-z][a-z0-9-]*$"
      examples:
        - "user-service"
        - "governance-engine"
        - "trust-manager"
      counter_examples:
        - "UserService"
        - "user_service"
        - "USER-SERVICE"
    
    # Version naming
    version_naming:
      pattern: "^\\d+\\.\\d+\\.\\d+$"
      examples:
        - "1.0.0"
        - "1.2.3"
        - "2.0.0"
      counter_examples:
        - "v1.0"
        - "1.0"
        - "1.0.0-beta"
    
    # Namespace naming
    namespace_naming:
      pattern: "^[a-z][a-z0-9-]*$"
      examples:
        - "machinenativeops-root"
        - "machinenativeops-governance"
        - "machinenativeops-modules"
      counter_examples:
        - "MachineNativeOps"
        - "machinenativeops_root"
        - "MACHINENATIVEOPS-ROOT"

  # === DEPENDENCY POLICIES ===
  dependency_policies:
    # DAG enforcement
    dag_enforcement:
      enabled: true
      strict: true
      circular_dependency_check: true
      auto_fix: false
    
    # Version constraints
    version_constraints:
      default_operator: ">="
      allow_wildcards: false
      allow_prerelease: false
      allow_build_metadata: false
    
    # Dependency health
    dependency_health:
      enabled: true
      check_interval: 300  # seconds
      timeout: 30  # seconds
      retry_attempts: 3

  # === VALIDATION RULES ===
  validation_rules:
    # Structural validation
    structural:
      enabled: true
      schema_validation: true
      required_fields_check: true
      data_type_check: true
    
    # Semantic validation
    semantic:
      enabled: true
      concept_consistency: true
      definition_completeness: true
      semantic_root_traceability: true
    
    # Dependency validation
    dependency:
      enabled: true
      dag_check: true
      circular_dependency_check: true
      version_compatibility: true
    
    # Governance validation
    governance:
      enabled: true
      naming_conventions: true
      documentation_completeness: true
      policy_compliance: true
    
    # Closure validation
    closure:
      enabled: true
      dependency_closure: true
      semantic_closure: true
      governance_closure: true

  # === SEMANTIC ROOT UPDATE MECHANISM ===
  update_mechanism:
    # Update triggers
    triggers:
      - type: "manual"
        enabled: true
        approval_required: true
      
      - type: "concept_extension"
        enabled: true
        approval_required: false
      
      - type: "breaking_change"
        enabled: true
        approval_required: true
      
      - type: "drift_detection"
        enabled: true
        approval_required: false
    
    # Update workflow
    workflow:
      steps:
        - name: "detect_change"
          description: "Detect semantic root change requirement"
        
        - name: "analyze_impact"
          description: "Analyze impact on all dependent artifacts"
        
        - name: "generate_reconciliation"
          description: "Generate backward reconciliation patches"
        
        - name: "validate_closure"
          description: "Validate semantic closure for all artifacts"
        
        - name: "request_approval"
          description: "Request approval if required"
        
        - name: "apply_update"
          description: "Apply semantic root update"
        
        - name: "update_artifacts"
          description: "Update dependent artifacts with reconciliation patches"
        
        - name: "verify_consistency"
          description: "Verify semantic consistency across all artifacts"
        
        - name: "generate_attestation"
          description: "Generate attestation bundle for update"
    
    # Update validation
    validation:
      pre_update:
        - "Validate semantic root version increment"
        - "Check breaking change declarations"
        - "Verify backward compatibility"
        - "Analyze dependency impact"
      
      post_update:
        - "Verify semantic closure"
        - "Validate all artifacts"
        - "Check drift detection"
        - "Generate attestation bundles"

  # === SEMANTIC ROOT CONSISTENCY MONITORING ===
  monitoring:
    # Metrics
    metrics:
      enabled: true
      prometheus:
        enabled: true
        endpoint: "/metrics"
        namespace: "machinenativeops_semantic_root"
      
      metrics_list:
        - name: "semantic_root_version"
          type: "gauge"
          description: "Current semantic root version"
        
        - name: "semantic_consistency_score"
          type: "gauge"
          description: "Semantic consistency score (0-1)"
        
        - name: "dependency_closure_status"
          type: "gauge"
          description: "Dependency closure status (0=fail, 1=pass)"
        
        - name: "governance_closure_status"
          type: "gauge"
          description: "Governance closure status (0=fail, 1=pass)"
        
        - name: "drift_detected"
          type: "counter"
          description: "Number of drift detections"
        
        - name: "reconciliation_generated"
          type: "counter"
          description: "Number of reconciliation patches generated"
    
    # Health checks
    health_checks:
      enabled: true
      endpoint: "/health"
      interval: 30  # seconds
      timeout: 10  # seconds
      
      checks:
        - name: "semantic_root_consistency"
          description: "Check semantic root consistency"
          critical: true
        
        - name: "dependency_closure"
          description: "Check dependency closure"
          critical: true
        
        - name: "semantic_closure"
          description: "Check semantic closure"
          critical: true
        
        - name: "governance_closure"
          description: "Check governance closure"
          critical: true

  # === ATTESTATION ===
  attestation:
    enabled: true
    format: "yaml"
    signing_enabled: true
    
    attestation_content:
      - "semantic_root_version"
      - "semantic_consistency"
      - "dependency_closure"
      - "semantic_closure"
      - "governance_closure"
      - "update_history"
      - "timestamp"
      - "signature"
    
    storage:
      path: "/root/.root.jobs/semantic-root-attestations/"
      retention: "7d"
      compression: true

status:
  phase: "active"
  version: "1.0.0"
  
  conditions:
    - type: "SemanticRootConsistency"
      status: "True"
      lastTransitionTime: "2025-01-10T10:00:00Z"
      reason: "Semantic root is consistent"
      message: "All concepts trace to semantic root, no drift detected"
    
    - type: "DependencyClosure"
      status: "True"
      lastTransitionTime: "2025-01-10T10:00:00Z"
      reason: "Dependency closure achieved"
      message: "All dependencies are resolvable, DAG is valid"
    
    - type: "SemanticClosure"
      status: "True"
      lastTransitionTime: "2025-01-10T10:00:00Z"
      reason: "Semantic closure achieved"
      message: "All artifacts are semantically consistent"
    
    - type: "GovernanceClosure"
      status: "True"
      lastTransitionTime: "2025-01-10T10:00:00Z"
      reason: "Governance closure achieved"
      message: "All governance policies are satisfied"