# MCP Policies - Machine Native Ops Namespaces MCP
# Governance Policy Entries
# Version: 1.0.0

apiVersion: mcp.io/v1
kind: Policy
metadata:
  name: io.github.machinenativeops/mcp-policies
  version: "1.0.0"
  description: "Governance policy entries for MCP platform"
  
  semanticType: "policy"
  mcpEndpoint: "/policies/validate"
  
  dependsOn:
    - artifact: "config/governance.yaml"
      purpose: "Governance framework"
  
  references:
    - artifact: "roles.yaml"
      purpose: "Role-based access control"

# Naming Convention Policy
namingConventionPolicy:
  name: "naming-convention-policy"
  version: "1.0.0"
  description: "Enforce MCP naming conventions"
  enforcement: "strict"
  
  rules:
    - id: "reverse-dns-naming"
      description: "Use reverse DNS naming for all artifacts"
      pattern: "^io\\.github\\.[a-z0-9-]+/[a-z0-9-]+$"
      applies: ["artifact names", "module names"]
      severity: "error"
      autoFix: false
    
    - id: "kebab-case-components"
      description: "Use kebab-case for component names"
      pattern: "^[a-z0-9-]+$"
      applies: ["component names", "file names"]
      severity: "error"
      autoFix: true
    
    - id: "semantic-versioning"
      description: "Use semantic versioning"
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+(-[a-z0-9]+)?$"
      applies: ["version numbers"]
      severity: "error"
      autoFix: false
    
    - id: "mcp-prefix"
      description: "Use 'mcp-' prefix for MCP modules"
      pattern: "^mcp-[a-z0-9-]+$"
      applies: ["module names"]
      severity: "warning"
      autoFix: false
  
  violations:
    - action: "reject"
      severity: "error"
    - action: "warn"
      severity: "warning"
  
  exemptions:
    - artifact: "legacy/*"
      reason: "Legacy artifacts exempt from naming rules"

# Dependency Policy
dependencyPolicy:
  name: "dependency-policy"
  version: "1.0.0"
  description: "Manage artifact dependencies"
  enforcement: "warning"
  
  rules:
    - id: "validate-dependency-versions"
      description: "Validate dependency version constraints"
      check: "version-constraint-valid"
      severity: "error"
    
    - id: "check-license-compatibility"
      description: "Check license compatibility"
      allowedLicenses: ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC"]
      prohibitedLicenses: ["GPL-3.0", "AGPL-3.0", "SSPL"]
      severity: "error"
    
    - id: "scan-vulnerabilities"
      description: "Scan for known vulnerabilities"
      maxCritical: 0
      maxHigh: 0
      maxMedium: 5
      severity: "error"
    
    - id: "detect-circular-dependencies"
      description: "Detect circular dependencies"
      check: "dependency-graph-acyclic"
      severity: "error"
    
    - id: "enforce-version-pinning"
      description: "Enforce version pinning for production"
      environment: "production"
      allowRanges: false
      severity: "warning"
  
  violations:
    - action: "reject"
      severity: "error"
    - action: "warn"
      severity: "warning"
  
  exemptions:
    - dependency: "experimental/*"
      reason: "Experimental dependencies exempt from strict rules"

# Security Policy
securityPolicy:
  name: "security-policy"
  version: "1.0.0"
  description: "Security baseline requirements"
  enforcement: "strict"
  
  rules:
    - id: "no-secrets-in-code"
      description: "No secrets in source code"
      check: "secret-detection"
      patterns:
        - "api[_-]?key"
        - "password"
        - "secret"
        - "token"
        - "private[_-]?key"
      severity: "error"
    
    - id: "mandatory-security-scan"
      description: "Mandatory security scanning"
      scanners: ["Snyk", "Trivy", "OWASP Dependency-Check"]
      frequency: "continuous"
      severity: "error"
    
    - id: "code-signing-required"
      description: "Code signing required for releases"
      algorithm: "RSA-4096"
      hash: "SHA3-512"
      severity: "error"
    
    - id: "encryption-at-rest"
      description: "Encryption at rest required"
      algorithm: "AES-256-GCM"
      applies: ["data storage", "backups"]
      severity: "error"
    
    - id: "encryption-in-transit"
      description: "Encryption in transit required"
      protocol: "TLS 1.3"
      minVersion: "TLS 1.2"
      severity: "error"
  
  violations:
    - action: "reject"
      severity: "error"
  
  exemptions: []

# Performance Policy
performancePolicy:
  name: "performance-policy"
  version: "1.0.0"
  description: "Performance baseline requirements"
  enforcement: "warning"
  
  rules:
    - id: "decision-latency"
      description: "Decision latency must be <100ms"
      target: "<100ms"
      percentile: "p99"
      severity: "warning"
    
    - id: "execution-latency"
      description: "Execution latency must be <500ms"
      target: "<500ms"
      percentile: "p99"
      severity: "warning"
    
    - id: "throughput"
      description: "Throughput must be >100 ops/sec"
      target: ">100"
      unit: "ops/sec"
      severity: "warning"
    
    - id: "success-rate"
      description: "Success rate must be >95%"
      target: ">95%"
      severity: "error"
    
    - id: "availability"
      description: "Availability must be >99.9%"
      target: ">99.9%"
      severity: "error"
  
  violations:
    - action: "warn"
      severity: "warning"
    - action: "reject"
      severity: "error"
  
  exemptions:
    - module: "experimental/*"
      reason: "Experimental modules exempt from performance requirements"

# Code Quality Policy
codeQualityPolicy:
  name: "code-quality-policy"
  version: "1.0.0"
  description: "Code quality standards"
  enforcement: "warning"
  
  rules:
    - id: "code-coverage"
      description: "Code coverage must be >80%"
      target: ">80%"
      severity: "warning"
    
    - id: "complexity"
      description: "Cyclomatic complexity must be <15"
      target: "<15"
      severity: "warning"
    
    - id: "duplicated-code"
      description: "Duplicated code must be <5%"
      target: "<5%"
      severity: "warning"
    
    - id: "documentation"
      description: "Public APIs must be documented"
      coverage: ">90%"
      severity: "warning"
    
    - id: "linting"
      description: "Code must pass linting"
      linters: ["ESLint", "Prettier"]
      severity: "error"
  
  violations:
    - action: "warn"
      severity: "warning"
    - action: "reject"
      severity: "error"

# Compliance Policy
compliancePolicy:
  name: "compliance-policy"
  version: "1.0.0"
  description: "Regulatory compliance requirements"
  enforcement: "strict"
  
  rules:
    - id: "gdpr-compliance"
      description: "GDPR compliance required"
      requirements:
        - "data-minimization"
        - "purpose-limitation"
        - "storage-limitation"
        - "right-to-erasure"
      severity: "error"
    
    - id: "audit-trail"
      description: "Audit trail required for critical operations"
      operations: ["data-modification", "access-control-changes", "policy-updates"]
      retention: "permanent"
      severity: "error"
    
    - id: "data-classification"
      description: "Data must be classified"
      levels: ["public", "internal", "confidential", "restricted"]
      severity: "error"
    
    - id: "access-control"
      description: "Access control required"
      mechanism: "RBAC"
      principle: "least-privilege"
      severity: "error"
  
  violations:
    - action: "reject"
      severity: "error"

# Deployment Policy
deploymentPolicy:
  name: "deployment-policy"
  version: "1.0.0"
  description: "Deployment requirements"
  enforcement: "strict"
  
  rules:
    - id: "approval-required"
      description: "Deployment approval required"
      approvers: 2
      roles: ["mcp_admin", "mcp_validator"]
      severity: "error"
    
    - id: "automated-tests"
      description: "Automated tests must pass"
      tests: ["unit", "integration", "security"]
      coverage: ">80%"
      severity: "error"
    
    - id: "rollback-plan"
      description: "Rollback plan required"
      automatic: true
      triggers: ["test-failure", "security-violation"]
      severity: "error"
    
    - id: "canary-deployment"
      description: "Canary deployment for production"
      environment: "production"
      percentage: "10%"
      duration: "1 hour"
      severity: "warning"
  
  violations:
    - action: "reject"
      severity: "error"
    - action: "warn"
      severity: "warning"

# Policy Enforcement
policyEnforcement:
  automated: true
  cicdIntegration: true
  
  checkpoints:
    - "pre-commit"
    - "pre-merge"
    - "pre-release"
    - "post-deployment"
  
  notifications:
    - channel: "slack"
      severity: ["error"]
    - channel: "email"
      severity: ["error", "warning"]
  
  reporting:
    frequency: "daily"
    format: "json"
    destination: "reports/policy-compliance/"

# Policy Metadata
metadata:
  createdAt: "2025-01-10T00:00:00Z"
  updatedAt: "2025-01-10T00:00:00Z"
  policyVersion: "1.0.0"
  totalPolicies: 7
  totalRules: 35
  compliance:
    - "MCP Level 1 Standards"
    - "Artifact-First Workflow"
    - "INSTANT Execution Standards"