# MCP Roles - Machine Native Ops Namespaces MCP
# Role-Based Access Control
# Version: 1.0.0

apiVersion: mcp.io/v1
kind: Role
metadata:
  name: io.github.machinenativeops/mcp-roles
  version: "1.0.0"
  description: "Role-based access control for MCP platform"
  
  semanticType: "role"
  mcpEndpoint: "/roles/validate"
  
  dependsOn:
    - artifact: "config/governance.yaml"
      purpose: "Governance framework"

# Role Definitions

## Publisher Role
mcpPublisher:
  name: "mcp_publisher"
  displayName: "MCP Publisher"
  description: "Role for publishing MCP artifacts"
  
  permissions:
    artifacts:
      - "artifact:create"
      - "artifact:read"
      - "artifact:update"
      - "artifact:publish"
    
    metadata:
      - "metadata:read"
      - "metadata:update"
    
    namespace:
      - "namespace:read"
      - "namespace:manage"
    
    versions:
      - "version:create"
      - "version:read"
      - "version:tag"
  
  restrictions:
    - "Cannot publish to production without approval"
    - "Cannot modify governance policies"
    - "Cannot delete published artifacts"
    - "Must pass all validation checks"
  
  requirements:
    authentication: "OAuth 2.0"
    mfa: false
    namespaceOwnership: true
  
  auditLevel: "detailed"

## Validator Role
mcpValidator:
  name: "mcp_validator"
  displayName: "MCP Validator"
  description: "Role for validating MCP artifacts"
  
  permissions:
    artifacts:
      - "artifact:read"
      - "artifact:validate"
    
    policies:
      - "policy:read"
      - "policy:enforce"
    
    compliance:
      - "compliance:check"
      - "compliance:report"
    
    audit:
      - "audit:read"
      - "audit:review"
    
    approvals:
      - "approval:grant"
      - "approval:deny"
  
  restrictions:
    - "Cannot modify artifacts"
    - "Cannot modify governance policies"
    - "Must follow validation procedures"
  
  requirements:
    authentication: "OAuth 2.0"
    mfa: true
    certification: "MCP Validator Certification"
  
  auditLevel: "comprehensive"

## Administrator Role
mcpAdmin:
  name: "mcp_admin"
  displayName: "MCP Administrator"
  description: "Role for administering MCP platform"
  
  permissions:
    registry:
      - "registry:read"
      - "registry:write"
      - "registry:manage"
      - "registry:configure"
    
    policies:
      - "policy:read"
      - "policy:write"
      - "policy:configure"
      - "policy:enforce"
    
    users:
      - "user:read"
      - "user:create"
      - "user:update"
      - "user:delete"
      - "user:manage-roles"
    
    system:
      - "system:read"
      - "system:configure"
      - "system:audit"
      - "system:backup"
      - "system:restore"
    
    security:
      - "security:read"
      - "security:configure"
      - "security:audit"
  
  restrictions:
    - "Requires multi-factor authentication"
    - "All actions must be audited"
    - "Cannot bypass security policies"
  
  requirements:
    authentication: "OAuth 2.0"
    mfa: true
    certification: "MCP Administrator Certification"
    backgroundCheck: true
  
  auditLevel: "comprehensive"

## Developer Role
mcpDeveloper:
  name: "mcp_developer"
  displayName: "MCP Developer"
  description: "Role for developing MCP artifacts"
  
  permissions:
    artifacts:
      - "artifact:create"
      - "artifact:read"
      - "artifact:update"
    
    development:
      - "dev:read"
      - "dev:write"
      - "dev:test"
    
    documentation:
      - "docs:read"
      - "docs:write"
    
    tools:
      - "tools:read"
      - "tools:use"
  
  restrictions:
    - "Cannot publish to production"
    - "Cannot modify governance policies"
    - "Limited to development environment"
  
  requirements:
    authentication: "OAuth 2.0"
    mfa: false
  
  auditLevel: "standard"

## Quantum Researcher Role
mcpQuantumResearcher:
  name: "mcp_quantum_researcher"
  displayName: "MCP Quantum Researcher"
  description: "Role for quantum-agentic research"
  
  permissions:
    quantum:
      - "quantum:read"
      - "quantum:experiment"
      - "quantum:analyze"
    
    research:
      - "research:read"
      - "research:write"
      - "research:publish"
    
    data:
      - "data:read"
      - "data:analyze"
    
    experimental:
      - "experimental:read"
      - "experimental:write"
      - "experimental:test"
  
  restrictions:
    - "Only experimental namespace"
    - "Must comply with research ethics"
    - "Cannot access production data"
  
  requirements:
    authentication: "OAuth 2.0"
    mfa: false
    certification: "Quantum Computing Certification"
  
  auditLevel: "standard"

## Auditor Role
mcpAuditor:
  name: "mcp_auditor"
  displayName: "MCP Auditor"
  description: "Role for auditing MCP platform"
  
  permissions:
    audit:
      - "audit:read"
      - "audit:review"
      - "audit:report"
      - "audit:export"
    
    compliance:
      - "compliance:read"
      - "compliance:review"
      - "compliance:report"
    
    security:
      - "security:read"
      - "security:review"
    
    logs:
      - "logs:read"
      - "logs:search"
      - "logs:export"
  
  restrictions:
    - "Read-only access"
    - "Cannot modify any artifacts"
    - "Cannot modify policies"
  
  requirements:
    authentication: "OAuth 2.0"
    mfa: true
    certification: "Security Auditor Certification"
  
  auditLevel: "comprehensive"

## Viewer Role
mcpViewer:
  name: "mcp_viewer"
  displayName: "MCP Viewer"
  description: "Role for viewing MCP artifacts"
  
  permissions:
    artifacts:
      - "artifact:read"
    
    documentation:
      - "docs:read"
    
    public:
      - "public:read"
  
  restrictions:
    - "Read-only access"
    - "Cannot modify any artifacts"
    - "Limited to public artifacts"
  
  requirements:
    authentication: "OAuth 2.0"
    mfa: false
  
  auditLevel: "minimal"

# Role Hierarchy
roleHierarchy:
  - level: 1
    roles: ["mcp_viewer"]
    description: "Basic read-only access"
  
  - level: 2
    roles: ["mcp_developer"]
    description: "Development access"
  
  - level: 3
    roles: ["mcp_publisher", "mcp_quantum_researcher"]
    description: "Publishing and research access"
  
  - level: 4
    roles: ["mcp_validator", "mcp_auditor"]
    description: "Validation and audit access"
  
  - level: 5
    roles: ["mcp_admin"]
    description: "Administrative access"

# Role Assignments
roleAssignments:
  byNamespace:
    "io.github.machinenativeops":
      admins: ["team@machinenativeops.com"]
      publishers: ["developers@machinenativeops.com"]
      validators: ["validators@machinenativeops.com"]
  
  byEnvironment:
    production:
      allowedRoles: ["mcp_admin", "mcp_validator", "mcp_auditor"]
      requiresApproval: true
    
    staging:
      allowedRoles: ["mcp_admin", "mcp_validator", "mcp_publisher", "mcp_developer"]
      requiresApproval: false
    
    development:
      allowedRoles: ["all"]
      requiresApproval: false
    
    experimental:
      allowedRoles: ["mcp_quantum_researcher", "mcp_developer"]
      requiresApproval: false

# Permission Matrix
permissionMatrix:
  artifacts:
    create: ["mcp_publisher", "mcp_developer", "mcp_admin"]
    read: ["all"]
    update: ["mcp_publisher", "mcp_developer", "mcp_admin"]
    delete: ["mcp_admin"]
    publish: ["mcp_publisher", "mcp_admin"]
    validate: ["mcp_validator", "mcp_admin"]
  
  policies:
    read: ["all"]
    write: ["mcp_admin"]
    configure: ["mcp_admin"]
    enforce: ["mcp_validator", "mcp_admin"]
  
  users:
    read: ["mcp_admin", "mcp_auditor"]
    create: ["mcp_admin"]
    update: ["mcp_admin"]
    delete: ["mcp_admin"]
    manage-roles: ["mcp_admin"]
  
  audit:
    read: ["mcp_auditor", "mcp_admin"]
    review: ["mcp_auditor", "mcp_admin"]
    report: ["mcp_auditor", "mcp_admin"]
    export: ["mcp_auditor", "mcp_admin"]

# Access Control Rules
accessControlRules:
  - name: "namespace-ownership"
    description: "Users can only publish to namespaces they own"
    applies: ["mcp_publisher"]
    enforcement: "strict"
  
  - name: "production-approval"
    description: "Production deployments require approval"
    applies: ["mcp_publisher"]
    environment: "production"
    enforcement: "strict"
  
  - name: "mfa-required"
    description: "MFA required for privileged roles"
    applies: ["mcp_admin", "mcp_validator", "mcp_auditor"]
    enforcement: "strict"
  
  - name: "audit-all-actions"
    description: "All actions by privileged roles must be audited"
    applies: ["mcp_admin", "mcp_validator"]
    enforcement: "strict"

# Role Metadata
metadata:
  createdAt: "2025-01-10T00:00:00Z"
  updatedAt: "2025-01-10T00:00:00Z"
  roleVersion: "1.0.0"
  totalRoles: 7
  compliance:
    - "MCP Level 1 Standards"
    - "Artifact-First Workflow"
    - "RBAC Best Practices"
    - "Least Privilege Principle"