# MCP Schema - Machine Native Ops Namespaces MCP
# JSON Schema Definitions for MCP Artifacts
# Version: 1.0.0

apiVersion: mcp.io/v1
kind: Schema
metadata:
  name: io.github.machinenativeops/mcp-schema
  version: "1.0.0"
  description: "JSON Schema definitions for MCP artifacts"
  
  semanticType: "schema"
  mcpEndpoint: "/schema/validate"
  
  references:
    - artifact: "spec.yaml"
      purpose: "Functional specifications"

# Manifest Schema
manifestSchema:
  $schema: "http://json-schema.org/draft-07/schema#"
  type: "object"
  required: ["apiVersion", "kind", "metadata", "dependencies"]
  properties:
    apiVersion:
      type: "string"
      pattern: "^mcp\\.io/v[0-9]+$"
      description: "MCP API version"
    
    kind:
      type: "string"
      enum: ["Manifest", "Schema", "Spec", "Governance", "Policy", "Role"]
      description: "Artifact kind"
    
    metadata:
      type: "object"
      required: ["name", "version", "description"]
      properties:
        name:
          type: "string"
          pattern: "^io\\.github\\.[a-z0-9-]+/[a-z0-9-]+$"
          description: "Reverse DNS naming"
        
        version:
          type: "string"
          pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+(-[a-z0-9]+)?$"
          description: "Semantic versioning"
        
        description:
          type: "string"
          minLength: 10
          maxLength: 500
          description: "Artifact description"
        
        author:
          type: "string"
          description: "Artifact author"
        
        license:
          type: "string"
          description: "License identifier"
        
        mcpVersion:
          type: "string"
          pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
          description: "MCP version (YYYY-MM-DD)"
    
    dependencies:
      type: "object"
      description: "Artifact dependencies"
      patternProperties:
        "^[a-z0-9-]+$":
          type: "object"
          required: ["artifact", "version", "required"]
          properties:
            artifact:
              type: "string"
              description: "Dependency artifact name"
            
            version:
              type: "string"
              description: "Version constraint"
            
            required:
              type: "boolean"
              description: "Is dependency required"
            
            purpose:
              type: "string"
              description: "Dependency purpose"

# Module Schema
moduleSchema:
  $schema: "http://json-schema.org/draft-07/schema#"
  type: "object"
  required: ["name", "version", "description", "path"]
  properties:
    name:
      type: "string"
      pattern: "^io\\.github\\.[a-z0-9-]+/mcp-[a-z0-9-]+$"
      description: "Module name with MCP prefix"
    
    version:
      type: "string"
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
      description: "Module version"
    
    description:
      type: "string"
      minLength: 10
      description: "Module description"
    
    path:
      type: "string"
      pattern: "^src/[a-z0-9-/]+$"
      description: "Module path"
    
    experimental:
      type: "boolean"
      default: false
      description: "Is module experimental"
    
    components:
      type: "array"
      items:
        type: "string"
        pattern: "^[a-z0-9-]+$"
      description: "Module components"

# Endpoint Schema
endpointSchema:
  $schema: "http://json-schema.org/draft-07/schema#"
  type: "object"
  required: ["path", "method", "description"]
  properties:
    path:
      type: "string"
      pattern: "^/[a-z0-9-/]+$"
      description: "Endpoint path"
    
    method:
      type: "string"
      enum: ["GET", "POST", "PUT", "DELETE", "PATCH"]
      description: "HTTP method"
    
    description:
      type: "string"
      minLength: 10
      description: "Endpoint description"
    
    parameters:
      type: "object"
      description: "Endpoint parameters"
    
    responses:
      type: "object"
      description: "Endpoint responses"

# Dependency Identifier Schema
dependencyIdentifierSchema:
  $schema: "http://json-schema.org/draft-07/schema#"
  type: "object"
  required: ["identifier", "version", "purpose"]
  properties:
    identifier:
      type: "string"
      pattern: "^[a-z0-9@/-]+@[0-9]+\\.[0-9]+\\.[0-9]+$"
      description: "Dependency identifier (name@version)"
    
    artifact:
      type: "string"
      description: "Related artifact"
    
    version:
      type: "string"
      description: "Version constraint"
    
    versionConstraint:
      type: "string"
      pattern: "^(>=|<=|>|<|=|~|\\^)[0-9]+\\.[0-9]+\\.[0-9]+$"
      description: "Version constraint operator"
    
    purpose:
      type: "string"
      minLength: 5
      description: "Dependency purpose"
    
    type:
      type: "string"
      enum: ["build-tool", "type-definition", "mcp-standard", "quantum-computing", "ai-reasoning"]
      description: "Dependency type"
    
    mandatory:
      type: "boolean"
      description: "Is dependency mandatory"
    
    experimental:
      type: "boolean"
      default: false
      description: "Is dependency experimental"

# Mapping Key Schema
mappingKeySchema:
  $schema: "http://json-schema.org/draft-07/schema#"
  type: "object"
  required: ["key", "source", "target", "type"]
  properties:
    key:
      type: "string"
      pattern: "^[a-z0-9-]+:[a-z0-9-]+$"
      description: "Mapping key (source:target)"
    
    source:
      type: "string"
      description: "Source artifact"
    
    target:
      type: "string"
      description: "Target artifact"
    
    type:
      type: "string"
      enum: ["structure-definition", "structure-to-behavior", "definition-to-policy", "computational-flow", "layer-abstraction"]
      description: "Mapping type"
    
    description:
      type: "string"
      minLength: 10
      description: "Mapping description"

# Reference Tag Schema
referenceTagSchema:
  $schema: "http://json-schema.org/draft-07/schema#"
  type: "object"
  required: ["tag", "artifact", "state"]
  properties:
    tag:
      type: "string"
      pattern: "^[a-z0-9-]+#[a-z0-9-]+$"
      description: "Reference tag (artifact#state)"
    
    artifact:
      type: "string"
      description: "Referenced artifact"
    
    state:
      type: "string"
      enum: ["validation-passed", "validation-active", "compliance-approved", "research-phase", "validator-operational", "experimental", "stable"]
      description: "Artifact state"
    
    description:
      type: "string"
      minLength: 10
      description: "Tag description"
    
    timestamp:
      type: "string"
      format: "date-time"
      description: "Tag timestamp"

# Namespace Verification Schema
namespaceVerificationSchema:
  $schema: "http://json-schema.org/draft-07/schema#"
  type: "object"
  required: ["method", "namespace", "validationStatus"]
  properties:
    method:
      type: "string"
      enum: ["github-oauth", "dns-txt", "http-well-known"]
      description: "Verification method"
    
    namespace:
      type: "string"
      pattern: "^io\\.github\\.[a-z0-9-]+$"
      description: "Namespace to verify"
    
    verificationEndpoint:
      type: "string"
      format: "uri"
      description: "Verification endpoint URL"
    
    requiredScopes:
      type: "array"
      items:
        type: "string"
      description: "Required OAuth scopes"
    
    validationStatus:
      type: "string"
      enum: ["pending", "verified", "failed"]
      description: "Validation status"
    
    verifiedAt:
      type: "string"
      format: "date-time"
      description: "Verification timestamp"

# Performance Metrics Schema
performanceMetricsSchema:
  $schema: "http://json-schema.org/draft-07/schema#"
  type: "object"
  properties:
    decisionLatency:
      type: "string"
      pattern: "^<[0-9]+ms$"
      description: "Decision latency target"
    
    executionLatency:
      type: "string"
      pattern: "^<[0-9]+ms$"
      description: "Execution latency target"
    
    parallelAgents:
      type: "string"
      pattern: "^[0-9]+-[0-9]+$"
      description: "Parallel agents range"
    
    successRate:
      type: "string"
      pattern: "^>[0-9]+%$"
      description: "Success rate target"
    
    availability:
      type: "string"
      pattern: "^>[0-9]+\\.[0-9]+%$"
      description: "Availability target"

# Validation Rules
validationRules:
  - name: "reverse-dns-naming"
    description: "Enforce reverse DNS naming convention"
    pattern: "^io\\.github\\.[a-z0-9-]+/[a-z0-9-]+$"
    applies: ["metadata.name", "modules.*.name"]
  
  - name: "semantic-versioning"
    description: "Enforce semantic versioning"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+(-[a-z0-9]+)?$"
    applies: ["metadata.version", "modules.*.version"]
  
  - name: "kebab-case"
    description: "Enforce kebab-case naming"
    pattern: "^[a-z0-9-]+$"
    applies: ["modules.*.components.*", "mappingKeys.*.key"]
  
  - name: "mcp-endpoint-format"
    description: "Enforce MCP endpoint format"
    pattern: "^/[a-z0-9-/]+$"
    applies: ["endpoints.*.path"]

# Custom Validators
customValidators:
  - name: "dependency-cycle-detection"
    description: "Detect circular dependencies"
    type: "graph-analysis"
    severity: "error"
  
  - name: "namespace-ownership"
    description: "Verify namespace ownership"
    type: "oauth-verification"
    severity: "error"
  
  - name: "semantic-boundary-check"
    description: "Check semantic boundaries"
    type: "semantic-analysis"
    severity: "warning"
  
  - name: "performance-target-validation"
    description: "Validate performance targets"
    type: "metric-validation"
    severity: "warning"

# Schema Metadata
metadata:
  createdAt: "2025-01-10T00:00:00Z"
  updatedAt: "2025-01-10T00:00:00Z"
  schemaVersion: "1.0.0"
  compliance:
    - "JSON Schema Draft 07"
    - "MCP Level 1 Standards"
    - "Artifact-First Workflow"